### ISSUE TITLE
Use lua-resty-socket to make this library useable without openresty

### ISSUE THREAD

**Issue by yangm97** [ledgetech/lua-resty-http#117]
I would like to use this library outside openresty, https://github.com/thibaultcha/lua-resty-socket promises an easy solution for that so why not? Bonus points for working around the lack of cosocket API on some openresty contexts.

**Comment by pintsized** [comment]
Outside of OpenResty I would recommend using: https://github.com/daurnimator/lua-http

**Comment by greatwolf** [comment]
> Outside of OpenResty I would recommend using: https://github.com/daurnimator/lua-http

It doesn't work under Windows though because of cqueue dependency.
