### ISSUE TITLE
 when will http2 protocol be supported?

### ISSUE THREAD

**Issue by ssdr** [ledgetech/lua-resty-http#123]
when will http2 protocol be supported in lua-resty-http module?

**Comment by pintsized** [comment]
Three years later, I guess no one got around to this. If anyone wants to sponsor this I'd be up for it. Likewise, PRs welcome.

**Comment by pintsized** [comment]
This is never going to happen here. http2 doesn't really fit into lua-nginx-module cosockets very well, and that situation hasn't changed as far as I can tell. Square peg / round hole.

There is this: https://github.com/tokers/lua-resty-http2

But it still has no TLS support and has to use the connection pool to work around the lack of persistent sessions.
