### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by lanss315425** [ledgetech/lua-resty-http#148]
@agentzh @pintsized hello! 
     Here's my code，version is 0.12
 `       local httpc = http.new()  `
 `       httpc:set_timeout(180000)`
 `       local content = {`
`		method = "POST",`
`		headers = {["content-type"]="application/json; charset=UTF-8"}`
`	}`
`	local res, err = httpc:request_uri(requrl..route, content)`
  `   --httpc:close()`
	`if not res then`
    `    ngx.log(ngx.ERR,"failed to request: "..tostring(requrl..route), err)      `
	`    return nil,err`
	`end`
        `return res.body,nil`

Here's the test results
   ![image](https://raw.githubusercontent.com/lanss315425/test/master/2018-05-2111-57-42.png)

**Comment by agentzh** [comment]
@lanss315425 Your leak flame graph does not show any real leaks. Everything seems to be in the nginx memory pool or something like that.

**Comment by agentzh** [comment]
@lanss315425 BTW, do not paste picture of the flame graph, please always provide the original SVG, otherwise a lot of info is abbreviated in the screen shot.

**Comment by agentzh** [comment]
@lanss315425 Are you sure you are really seeing a memory leak? Not just delays in LuaJIT's GC or glibc's allocator's freed memory block cache?

**Comment by agentzh** [comment]
@lanss315425 You should stress your nginx server with full load for hours and see if the memory usage grows without limit. Testing just individual requests do no good here due to intended delays in LuaJIT's GC or glibc's allocator's freed memory block cache for performance reasons.

**Comment by lanss315425** [comment]
I run the following script, and the memory is rising
`while true; do pmap -d  3066 | tail -1; sleep 2 ; done `
and I run this HTTP code in the ngx.timer.at loop of initwork.

**Comment by lanss315425** [comment]
@agentzh 
I also have a CPU question about AES, using "resty.aes", _VERSION ='0.10'.
![image](https://raw.githubusercontent.com/lanss315425/test/master/2018-05-2333333.png)

**Comment by agentzh** [comment]
@lanss315425 Such vague description is not very helpful. Please provide a minimal and standalone example that we can easily run on our side and reproduce the problem. How long have you stressed your service?

**Comment by agentzh** [comment]
@lanss315425 Please do not hijack this github issue for unrelated matter. It makes this thread confusing and twisting. Better ask general questions on the openresty-en mailing list. Also, your previous comment does not look like a question. I'm not seeing the question part.

**Comment by lanss315425** [comment]
@agentzh 
It took me two nights to test the code before I checked out the HTTP. The whole process was running at full capacity.

**Comment by lanss315425** [comment]
@agentzh OK, I will remove another problem to the new window.

**Comment by agentzh** [comment]
@lanss315425 I already said you should not paste the image of your flame graphs but provide the original SVG files, due to the information loss in the former format. You were not listening. Alas.

**Comment by agentzh** [comment]
@lanss315425 You should also make sure you are using the latest OpenResty formal release 1.13.6.2. You did not even mention the version of OpenResty (or nginx/ngx_lua) you are using. Alas.

**Comment by lanss315425** [comment]
@agentzh I uploaded the original file, https://raw.githubusercontent.com/lanss315425/test/master/mem.bt.

**Comment by lanss315425** [comment]
@agentzh I'm using the openresty 1.11.2.2 version

**Comment by agentzh** [comment]
@lanss315425 I asked for the SVG files but you provided the backtrace dump. The former would be much more convenient for us otherwise we had to run flamegraph.pl tool to generate the SVG files...

**Comment by agentzh** [comment]
@lanss315425 I said you should try the latest OpenResty 1.13.6.2, right? ;)

**Comment by lanss315425** [comment]
@agentzh 
Sorry, I'm a little nervous. I received your reply for the first time, https://raw.githubusercontent.com/lanss315425/test/master/2018051900.svg

**Comment by agentzh** [comment]
@lanss315425 Also, I said your leak flame graph does not indicate any real leaks. You should sample for minutes or hours to generate a leak flame graph, depending on the leak rate you are observing. If the memory is not growing without bound in hours, then it's not a leak.

**Comment by lanss315425** [comment]
@agentzh This is the pmap -d log I grab every 5 seconds, https://raw.githubusercontent.com/lanss315425/test/master/memlog

**Comment by agentzh** [comment]
@lanss315425 I'm seeing a lot of allocations in your libcrypto.so in your latest memory leak flame graph. But your system's libcrypto.so lacks debuginfo so all those allocations lack any backtraces in the graph, which is not helpful for analyses.

You should install the debuginfo package for your system's openssl package. Or better, disable the asm part in your openssl build by switching over to our openresty-debug pre-built package provided for many Linux distributions. See

https://openresty.org/en/linux-packages.html

**Comment by agentzh** [comment]
@lanss315425 We're not interested in debugging old versions of OpenResty. Please try reproducing it in the latest OpenResty version, as I said for twice above ;)
