### ISSUE TITLE
Kong Custom Plugin

### ISSUE THREAD

**Issue by sharmmoh1983** [ledgetech/lua-resty-http#159]
I am not able to  process JSON response 

```
 local httpc = http.new()
local res, err = httpc:request_uri("https://jsonplaceholder.typicode.com/todos/1", {
                    method = "GET",
ssl_verify = false,
                    headers = {
                    ["Content-Type"] = "application/json",
                    }
                })

local cjson = require "cjson"
local data = cjson.decode(res.body)
**ngx.log(ngx.ERR,data)**

```
`2018/10/04 14:22:07 [error] 600#0: *9839 [lua] responses.lua:121: access(): /usr/local/share/lua/5.1/kong/plugins/myplugin/handler.lua:80: bad argument #1 to 'log' (expected table to have __tostring metamethod)`

I am not able to log JSON  response coming from API . Also how to add SSL certificate to make successful connection

**Comment by pintsized** [comment]
Hi, apologies for the incredibly slow reply. You might want to ask for more general help on the OpenResty mailing list.

Your first issue is explained in the error message; `ngx.log` needs a string, but you're passing it a table.

For help with SSL certificates, again I suggest reading the OpenResty docs and seeking help on the mailing list; it's not specific to this module.
