### ISSUE TITLE
Hide debug logging behind a flag

### ISSUE THREAD

**Issue by Crack** [ledgetech/lua-resty-http#167]
Could you hide debug logging (`ngx_log(ngx_DEBUG, "\n", req)`) behind a flag? I have some code that doesn't need to have all of that logged. My logging is set to debug and that's not something I want to change.

**Comment by pintsized** [comment]
You have debug logging on in production? Well ok sure, if you want to send a PR I'd be happy to review it?

**Comment by hamishforbes** [comment]
Done in b02f3dc
