### ISSUE TITLE
bad body reader caller without chunksize specified

### ISSUE THREAD

**Issue by ssdr** [ledgetech/lua-resty-http#169]
https://github.com/ledgetech/lua-resty-http/blob/e5deba5bde1db31adc7aad574bae5e89f83fd973/lib/resty/http.lua#L543

Here when *body* is a function, it's better to call it with a chunk size spicified, for streaming reason.

**Comment by ssdr** [comment]
#171 I issue a pull request for this :smile_cat:

**Comment by hamishforbes** [comment]
The function request body function provided by a user should be an iterator style function.    
It is up to the user to determine the chunksize within that function. 

Similar to how the built in body reader function has a generator function which specifies the chunksize https://github.com/ledgetech/lua-resty-http/blob/e5deba5bde1db31adc7aad574bae5e89f83fd973/lib/resty/http.lua#L920

**Comment by ssdr** [comment]
> The function request body function provided by a user should be an iterator style function.
> It is up to the user to determine the chunksize within that function.
> 
> Similar to how the built in body reader function has a generator function which specifies the chunksize
> 
> [lua-resty-http/lib/resty/http.lua](https://github.com/ledgetech/lua-resty-http/blob/e5deba5bde1db31adc7aad574bae5e89f83fd973/lib/resty/http.lua#L920)
> 
> Line 920 in [e5deba5](/ledgetech/lua-resty-http/commit/e5deba5bde1db31adc7aad574bae5e89f83fd973)
> 
>  function _M.get_client_body_reader(_, chunksize, sock)

I don't think so...
_M.get_client_body_reader() is a read side reader function, indeed it's user's responsibility to determine then chunksize within it.
But, I am talking about the send side function. When you upload a huge file which gets from upstream,
if you don't specifies a chunksize for body(), you'll cache the whole file locally before uploading, or maybe LuaVM crash for memory reason.

**Comment by hamishforbes** [comment]
Can you provide some example code?

The body function you provide is called when resty-http want's to send more data, its up to you / that function to return the next #chunk bytes.
This is exactly how the built-in request body reader works.

**Comment by hamishforbes** [comment]
Ah ok, I see.

You should wrap the body_reader in a function that provides your chunk size. 
e.g.

```lua
-- get data from upstream
local res1, err = http1:request({
        method = "GET",
        path = "/path/to/huge_file",
        headers = req_header1
    })
local function body_uploader()
     return res1.body_reader(65535)
end
-- upload data to somewhere
local res2, err = http2:request({
        method = "POST",
        path = "/path/to/huge_file",
        headers = req_header2,
        body = body_uploader,
    })
```

**Comment by ssdr** [comment]
emmm, ok, maybe this is better usage... i close this issue.
