### ISSUE TITLE
problem of keepalive pool

### ISSUE THREAD

**Issue by oasfuyou** [ledgetech/lua-resty-http#178]
when i read the words below:

-- The server said we must close the connection, so we cannot setkeepalive.
        -- If close() succeeds we return 2 instead of 1, to differentiate between
        -- a normal setkeepalive() failure and an intentional close().

if when the local res, err=sock:setkeepalive(...),if the res=1,means setkeepalive failed????

_Originally posted by @oasfuyou in https://github.com/ledgetech/lua-resty-http/issues/160#issuecomment-476563297_

**Comment by pintsized** [comment]
`1` indicates success. See the docs: https://github.com/ledgetech/lua-resty-http#set_keepalive
