### ISSUE TITLE
The old system used independent nginx to compile and install LuaJIT-2.0.5.tar.gz. How to use lua-resty-http

### ISSUE THREAD

**Issue by mpv945** [ledgetech/lua-resty-http#182]
At present, the Lua file downloaded from lua-resty-http is placed in the / usr/local/lua jit/share/luajit-2.0.5/jit/directory.
Nginx configuration lua_package_path'/usr/local/lua jit/share/luajit-2.0.5/jit/?.lua;'
After this configuration, write local HTTP = require ("resty. http"), and the application will not run.

**Comment by hamishforbes** [comment]
https://github.com/openresty/lua-nginx-module/#lua_package_path
