### ISSUE TITLE
Add content-length header for POST requests

### ISSUE THREAD

**Issue by StuAtKong** [ledgetech/lua-resty-http#184]
According to the RFC, POST requests SHOULD contain a content-length header even if there is no body attached i.e. "content-length:0" unless there is a Transfer-Encoding header.

https://tools.ietf.org/html/rfc7230#section-3.3.2

The library only adds a content length header if there is a body in the request;
https://github.com/ledgetech/lua-resty-http/blob/23053ba93117116de2e50749c7a448e6e840914b/lib/resty/http.lua#L606

Can this be modified to add the header for POST requests that do not contain a body?

**Comment by hamishforbes** [comment]
That looks like a correct improvement to me, it's only a *should* though so not a critical change I think.
Pull Requests are welcome, but we'll need to be a little careful with fixing this as there are a few conditions to consider from the RFC.
Also in the case where the body is provided as a function it is up to the user to ensure the headers are set correctly as we cannot help in that scenario.

**Comment by shaynevanasperen** [comment]
I'd just like to point out that although the RFC specifies that it is a SHOULD and not a MUST, there are at least 3 major web servers that treat is as a MUST:
- IIS
- Kestrel
- Nginx

**Comment by hamishforbes** [comment]
> I'd just like to point out that although the RFC specifies that it is a SHOULD and not a MUST, there are at least 3 major web servers that treat it as a MUST:
> 
> * IIS
> * Kestrel
> * Nginx

That's interesting, what actually happens if you send a POST with no body and no content-length to these servers?

**Comment by shaynevanasperen** [comment]
> That's interesting, what actually happens if you send a POST with no body and no content-length to these servers?

They respond with a 411 status code.

**Comment by hamishforbes** [comment]
Released in v0.14 :)
