### ISSUE TITLE
0.14 not released on LuaRocks

### ISSUE THREAD

**Issue by bungle** [ledgetech/lua-resty-http#186]
Could you please also release the `0.14` on `luarocks`?
https://luarocks.org/modules/pintsized/lua-resty-http

Thank you!

**Comment by bungle** [comment]
ping @pintsized, any possibilities to update that? Thanks :-)!

**Comment by bungle** [comment]
ping @hamishforbes, do you have an idea how we could proceed this. I ask this as we would like to bump the version dependency on https://github.com/kong/kong, and we would prefer not to fork the project just for that.

**Comment by pintsized** [comment]
Hey, very sorry for not responding, I'm on a sabbatical and have been travelling. So `v0.14` is all prepared, just needs pushing to luarocks? I can do that now.

**Comment by hamishforbes** [comment]
Can we move the Luarock under a shared namespace as well, like the OPM release is?

**Comment by pintsized** [comment]
Yeah was thinking the same, just wondering about how that redirects for people?

**Comment by bungle** [comment]
I can ask @hishamhm to change default `resty-http` to then like to shared namespace on `luarocks`.

**Comment by bungle** [comment]
Or perhaps @hishamhm can help you just moving the `resty-http` from `pintsized` to `ledgetech`?

**Comment by pintsized** [comment]
Lol sorry I guys I'm making a real mess of this. Should have started with coffee. I need to bump to v0.15 to update the rockspec, but yes after that does it need to live in a different luarocks account?

**Comment by pintsized** [comment]
Ok so we have a new tag (v0.15). I can push this to luarocks as `pintsized`, or create a new account on luarocks, and share the API key with you @hamishforbes - is that what you mean?

**Comment by hamishforbes** [comment]
Hmm, looks like luarocks doesn't have a concept of a shared account/namespace in the same way as OPM/Github orgs do.

I think probably just publish 0.15 under pintsized to get it out and we can figure out what to do afterwards?

**Comment by pintsized** [comment]
Ok

**Comment by pintsized** [comment]
Ok that's done. `v0.14` and `v0.15` are actually the same, just `v0.15` has `ledgetech` URIs in the rockspec, but that doesn't make any difference I guess.
