### ISSUE TITLE
res.read_body() and res.body

### ISSUE THREAD

**Issue by GildedHonour** [ledgetech/lua-resty-http#187]
What's the difference between these?
```

local res, err = http_client:request_uri(some_url)
-- res.body vs res.read_body()
```

**Comment by hamishforbes** [comment]
When using the simple interface (`request_uri`) the body is automatically read for you and available as `res.body`.

When using the generic interface (`request`) the body is *not* read and you can choose to read it all into a single Lua variable (`res.read_body()`) or using an iterator (`res.body_reader`)
