### ISSUE TITLE
how to use this library to implement balancer?

### ISSUE THREAD

**Issue by miaovictor** [ledgetech/lua-resty-http#188]
As we know, we can use upstream to implement balancer, but in my code, i use lua-resty-http to request backend service, i must choose a service from service list, this is balancer,but not use upstream.

Can you tell me how to implement balancer by a better way?

**Comment by hamishforbes** [comment]
You cannot with this library, you have to implement balancing yourself or use another library on top of this one.
e.g. https://github.com/hamishforbes/lua-resty-upstream

See https://github.com/bungle/awesome-resty for a curated list of various libraries 
also http://opm.openresty.org/ and the mailing list https://groups.google.com/forum/?fromgroups=#!forum/openresty-en
