### ISSUE TITLE
http.lua:xxx: send_request() problem?

### ISSUE THREAD

**Issue by bumi001** [ledgetech/lua-resty-http#189]
Hi I see the following in the nginx log for one of my server blocks, say, xxxx:

2019/08/XX XX:XX:XX [debug] XXXXX#XXXXXX: *XXXX [lua] http.lua:xxx: send_request(): 
POST /report_abuse HTTP/1.1
host: yyyy  <---- ANOTHER ONE OF MY SERVER BLOCK

It looks to me that they are able to force http.lua to send arbitrary requests. Is there a way to discuss this in private?

**Comment by bumi001** [comment]
It seems to me that the function _format_request doesn't handle the body component of the params table. So, I am wondering if someone can explain how the body is handled before send_request is called or how body is passed to send_request.

**Comment by bumi001** [comment]
I understand what is happening. A second request is hidden in params.body. The first request is crafted such that sock:send(req) completes normally. Then, _send_body(sock, body) sends the second request.

**Comment by pintsized** [comment]
I believe this should no longer be possible since `v0.16`, since the classic "request smuggling" technique is now explicitly mitigated. Perhaps you are able to confirm?
