### ISSUE TITLE
how to post a json？？

### ISSUE THREAD

**Issue by zhidd** [ledgetech/lua-resty-http#192]
local http = require "resty.http"
      local httpc = http.new()
      local res, err = httpc:request_uri("http://ip:9200/post/_search", {
        method = "GET",
        body = cjson.decode({"query":{"bool":{"must":[{"match":{"title":"adsense"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"aggs":{}}),
        headers = {
          ["Content-Type"] = "application/json; charset=utf-8",
        },
        keepalive_timeout = 60,
        keepalive_pool = 10
      })

  ngx.say(res.body)

**Comment by zhidd** [comment]
: *3 failed to load external Lua file "./lua_script/app.lua": ./lua_script/app.lua:14: '}' expected near ':', client: 127.0.0.1

**Comment by hamishforbes** [comment]
You're trying to put a literal json object into Lua source code, obviously that is not going to work.
You need to make it a string before you do anything
https://www.lua.org/manual/5.3/manual.html#3.1
