### ISSUE TITLE
there is no body when i sent a request

### ISSUE THREAD

**Issue by 99848873** [ledgetech/lua-resty-http#195]
i want use request_uri to sent a http request，and the request need a json body like this.
local datas =  {msgtype = "text",text= {content= "hello world" }}
    local res , err = httpc:request_uri("http://in.qyapi.weixin.qq.com",{
        methot = "POST",
           headers  = {
                ["Content-Type"] = "application/json",
           },
        body = json.encode(datas)
    })
but when i sent this request , i will get a err respone tell me that my json is not right.
i find someone help me check my request , he said my request only have '{' in body.

can you help me slove this issue

**Comment by pintsized** [comment]
Sorry for the very slow reply, but this is unlikely to be related to this module. Check your output string from `json.encode`, and maybe ask for general help on openresty channels like the mailing list.
