### ISSUE TITLE
attempt to call method 'set_proxy_options' (a nil value)

### ISSUE THREAD

**Issue by 99848873** [ledgetech/lua-resty-http#196]
local httpc = http.new()
    httpc:set_proxy_options({
        http_proxy = "http://devnet-proxy.oa.com:8080",
        https_proxy = "https_proxy=http://devnet-proxy.oa.com:8080"
    })

my code like this 
bug i got the error 
attempt to call method 'set_proxy_options' (a nil value)

**Comment by pintsized** [comment]
Perhaps you have a very old version of this module (if that method really doesn't exist)?
