### ISSUE TITLE
[Feature Request] Allow to set request level timeout

### ISSUE THREAD

**Issue by spacewander** [ledgetech/lua-resty-http#204]
Currently, the `set_timeouts` method only set the timeout of per-operation level. This is no enough in some situation. For instance, if the user set the timeout to 5s, and a HTTP request may contain 10 times of read operation, the final time spent may be 10 * 5s = 50s. Sometimes the user just wants a request level timeout instead.

We can implement this with timeout check before
* each write operation
* each read operation

For pipeline requests, the timeout should be applied to all requests, since we only starts to read after all requests are sent.

If this feature is desirable, I am willing to contribute a pull request when I have enough spare time.

**Comment by pintsized** [comment]
This library aims to be a cosocket driver implementing HTTP, and as such is relatively low level. i.e. it's not `curl`. I think what you're looking for is a higher level feature, and you should be able to implement that for your case, using `lua-resty-http` as your driver.
