### ISSUE TITLE
Request a service for a long time to return results.

### ISSUE THREAD

**Issue by sunnykandy** [ledgetech/lua-resty-http#207]
Using "lua-resy-http" as an HTTP client to access HTTP services will take about 3 to 8 seconds to get results, but using a browser will get results soon.

`local http = require 'resty.http'`
`local client = http:new()`
`local resp,err = client:request_uri(string.format(url,code),{`
         `method = 'GET',`
         `header = {},`
         `ssl_verify = false,`
        ` keepalive_timeout = 60,`
       ` keepalive_pool = 10`
`    })`
`

**Comment by pintsized** [comment]
It's extremely unlikely to be an issue with this module (which is widely used in a variety of performance critical contexts). Your browser is likely setting headers which allow for a cached response, for example.
