### ISSUE TITLE
Connection closed when call sock:receive(content_length)

### ISSUE THREAD

**Issue by stefli** [ledgetech/lua-resty-http#215]
We use resty.http to call the external service, but it always returns nil.
keepalive: true

headers:
> 727: request(): Strict-Transport-Security:max-age=86400
727: request(): Content-Length:70
727: request(): Server:testServer
727: request(): Content-Type:text/plain; charset=utf-8
727: request(): Date:Wed, 12 Aug 2020 09:52:31 GMT
727: request(): Access-Control-Allow-Credentials:true
727: request(): Connection:keep-alive

No Transfer-Encoding header exists, so it'll not go to _chunked_body_reader() function.

When calling the below lines, it will cause a connection close issue and return nil.
`elseif not max_chunk_size then
    -- We have a length and potentially keep-alive, but want everything.
    co_yield(sock:receive(content_length))`
I have found that the content-length is too short(Content-Lengh=70) may cause failure. So if use receive('*a') to get the response, it works.

**Comment by pintsized** [comment]
I'm not sure I understand completely, but yes, if you have a `Content-Length` with an incorrect value, then expect problems. If the length cannot be properly known in advance, omit the header.

**Comment by stefli** [comment]
> I'm not sure I understand completely, but yes, if you have a `Content-Length` with an incorrect value, then expect problems. If the length cannot be properly known in advance, omit the header.

The `Content-Length` returned by the server which I can't control. Do you mean that the `Content-Length` value is not equal to the response body length?

**Comment by pintsized** [comment]
I thought that was what you were suggesting; and yes if the `Content-Length` is wrong you'll have problems - too long and it will try to read from a closed socket (sounds like what you're getting?), and too short you'll probably have issues with keepalive.

Can you post a minimal example that demonstrates your problem? Including the specific error string you might get whilst trying to read for example.

**Comment by stefli** [comment]
@pintsized here is a sample configuration that may reproduce the issue.
Server-side
`
server {
  listen 8899;
  lua_code_cache on;
  lua_need_request_body on;
  location / {
    resolver 114.114.114.114;
    content_by_lua '
      local result = [[{"flag":"success","code":"200","message":"success invoked"}]]
      ngx.header["Content-Type"] = "text/plain; charset=utf-8"
      ngx.header["Content-Length"] = 70 -- The key result, wrong length calculated
      --ngx.header["Content-Length"] = #result
      ngx.say(result)
    ';
  }
}
`
Client-side(invoke the server-side by lua-resty-http)
`
server {
  listen 8897;
  lua_code_cache on;
  lua_need_request_body on;  
  location / {
    resolver 114.114.114.114;
    default_type application/json;
    content_by_lua '
      local zhttp = require("resty.http")
      local httpc = zhttp.new() 
      local body = ngx.req.get_body_data()
      local headers = ngx.req.get_headers()
      local _headers = {}
      _headers["Content-Type"] = "application/json; charset=utf-8"
      _headers["Connection"] = "close" -- Key settings for demostration
      local result, _err = httpc:request_uri("http://localhost:8899/", {
        method = "POST",
        ssl_verify = false,
        body = body,
        headers = _headers
      })
      if result then
        ngx.say(result.body)
      end
    ';
  }
}
`

Due to the wrong "Content-Length" returned by the server,  sock:receive() will get the connection closed error. But it works fine when returned the right "Content-Length".
I set the Connection to "close" to make sure the connection been closed immediately, otherwise, the invoking may return nothing until a timeout.

I'm asking for help from the service provider to figure out why to return a wrong Content-Length.

I'm not sure even plugin can correct the Content-Length from socket stream

**Comment by pintsized** [comment]
If you can't trust the content length to be correct (this is really bad, the provider really does need to fix it), you could try deleting that header from the response first. You would need to use the generic interface, not the simple `request_uri` interface (see the docs). First run the request, then remove the `Content-Length` response header, then call `res:read_body()`. That should work.

**Comment by stefli** [comment]
> If you can't trust the content length to be correct (this is really bad, the provider really does need to fix it), you could try deleting that header from the response first. You would need to use the generic interface, not the simple `request_uri` interface (see the docs). First run the request, then remove the `Content-Length` response header, then call `res:read_body()`. That should work.

ok, I'll try it later, thanks.

**Comment by stefli** [comment]
> If you can't trust the content length to be correct (this is really bad, the provider really does need to fix it), you could try deleting that header from the response first. You would need to use the generic interface, not the simple `request_uri` interface (see the docs). First run the request, then remove the `Content-Length` response header, then call `res:read_body()`. That should work.

I have tried to remove the header `Content-Length`, but it doesn't work.  
According the below lines:
> local res_headers, err = _receive_headers(sock)
    if not res_headers then
        return nil, err
    end
    ...
    -- Receive the body_reader
    if _should_receive_body(params.method, status) then
        local ok, encoding = pcall(str_lower, res_headers["Transfer-Encoding"])
        if ok and version == 1.1 and encoding == "chunked" then
            body_reader, err = _chunked_body_reader(sock)
            has_body = true
        else

            local ok, length = pcall(tonumber, res_headers["Content-Length"])
            if ok then
                body_reader, err = _body_reader(sock, length)
                has_body = true
            end
        end
    end

There is no way to change the response header before calling the _body_reader method.

My codes as below:
> local result, _err = httpc:request({
          path = "/",
          method = "POST",
          ssl_verify = false,
          body = body,
          headers = _headers
      })
      if not result then
        ngx.say("failed to request: ", err)
        return
      end
      result.headers["Content-Length"] = nil -- Not work
      -- result.headers["Transfer-Encoding"] = "chunked"  Not work
      for k, v in pairs(result.headers) do
        print(k .. "->" .. v)
      end
      if result.has_body then
        local res = result:read_body()
        ngx.say(res)
      else
        ngx.say("no body, no body!")
      end

Please tell me how to remove the header `Content-Length`.

**Comment by pintsized** [comment]
Sorry yes, you're right. The body reader gets set up with the length (if present) in the first stage, so there's no opportunity to interfere.

What does curl do, with the response from your provider? A bad content length really is very very broken.

**Comment by stefli** [comment]
> Sorry yes, you're right. The body reader gets set up with the length (if present) in the first stage, so there's no opportunity to interfere.
> 
> What does curl do, with the response from your provider? A bad content length really is very very broken.

I have tested the provider's service by curl, java, online post website, all can return the result even the Content-Length is incorrect.
Below is the result of the curl of the sample:
> [root@iZbp1j3y3a4thl1hhchdexZ nginx]# curl -v -XPOST -H "Connection: close" http://localhost:8899/
* About to connect() to localhost port 8899 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8899 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8899
> Accept: */*
> Connection: close
>
< HTTP/1.1 200 OK
< Server: openresty/1.13.6.1
< Date: Sat, 15 Aug 2020 14:58:54 GMT
< Content-Type: text/plain; charset=utf-8
< Connection: close
< Content-Length: 70
<
{"flag":"success","code":"200","message":"ok"}
* transfer closed with 23 bytes remaining to read
* Closing connection #0
curl: (18) transfer closed with 23 bytes remaining to read

**Comment by stefli** [comment]
@pintsized Curl works fine, so is there another solution to get response stream?

**Comment by pintsized** [comment]
Curl "works" but tells you there's a problem. The spec is clear that a response with an incorrect content length MUST be discarded. And this module isn't a replacement for a high level http client like curl, it's a low level driver.

I'm not saying it's impossible to accommodate this case, but I don't have time to do it right now, and it's not a bug - your provider needs to fix their service. Even if we get it working, you probably won't be able to reuse the connection.

If you can find a nice way of handling this gracefully, I am of course more than happy to discuss a PR. Please understand however that this code is really very widely deployed now (one of the most downloaded modules on luarocks), and so changes of this kind must be made carefully. If I sound evasive, that's basically why (the potential impact to continuously deployed systems).

**Comment by stefli** [comment]
> Curl "works" but tells you there's a problem. The spec is clear that a response with an incorrect content length MUST be discarded. And this module isn't a replacement for a high level http client like curl, it's a low level driver.
> 
> I'm not saying it's impossible to accommodate this case, but I don't have time to do it right now, and it's not a bug - your provider needs to fix their service. Even if we get it working, you probably won't be able to reuse the connection.
> 
> If you can find a nice way of handling this gracefully, I am of course more than happy to discuss a PR. Please understand however that this code is really very widely deployed now (one of the most downloaded modules on luarocks), and so changes of this kind must be made carefully. If I sound evasive, that's basically why (the potential impact to continuously deployed systems).

Thanks for your reply. And I agree with you that the provider needs to fix it.

**Comment by stefli** [comment]
@pintsized
Finally, the service provider fix the `Content-Length` issue, then all works fine.
