### ISSUE TITLE
Settimeout or Settimeouts aren't working as expected

### ISSUE THREAD

**Issue by cyberajit** [ledgetech/lua-resty-http#218]
Openresty v1.17.8.2
lua-resty-http v0.14

I'm trying to see if the http call made within lua code, honours the timeout so I tested it this way:

within content_by_lua :
```
    local timeout = 1000
    local endpoint_data = "127.0.0.1:7071"

    local http = require "resty.http"
    local httpc = http.new()
    httpc:set_timeout(timeout) -- does not seem to work
    local ok, res, err

    if timeout ~= nil then
        local args = ngx.req.get_uri_args(500)
        local host, port = endpoint_data:match("([^,]+):([^,]+)")
        ok, err = httpc:connect(host, port)
        if ok then
            local rule_params = {}
            local merged_args = util.merge_dictionary(args, rule_params)
            local params_table = {}
            params_table["query"] = merged_args
            params_table["path"] = ngx.var.uri
            params_table["method"] = ngx.req.get_method()
            params_table["headers"] = headers
            params_table["version"] = 1.1
            httpc:set_timeouts(100, 100, timeout) -- does not seem to work
            res, err = httpc:request(params_table)
       end
end
```

---------------------

To test this, I have a conf within nginx to delay the request by 5 sec

```
  server {
    listen 7071;
      location / {
        default_type text/html;
        content_by_lua '
        local start = os.clock()
        while os.clock() - start < 5 do end
        ngx.say("Delay success!!")';
      }
  }
```

When the call is made, it goes through without any issues. Ideally since the the response takes 5 secs, I was expecting the http call to fail due to time out exceeding, but does not happen so, am i missing something?

**Comment by cyberajit** [comment]
Upon digging further, it appears that when a call is made on `127.0.0.1` the timeout aren't applied, but if i replace the address with the machine's address it works. Is there a workaround or a fix for this?

**Comment by pintsized** [comment]
Hi, I'm not entirely sure why that would be the case, but regardless I suspect you are looking in the wrong place. The `set_timeout(s)` calls here just map directly onto the cosocket API (https://github.com/openresty/lua-nginx-module/#tcpsocksettimeout), and so if there is some special case for `127.0.0.1` then I'd start looking there.

Does seem odd however.
