### ISSUE TITLE
Question: How to make certificate authentication with resty-http?

### ISSUE THREAD

**Issue by balamutik** [ledgetech/lua-resty-http#221]
Hello!
I need to send a request with resty-http to a host, which accepts only authentication with certificate.
How can i perform it?

Thank you.

**Comment by balamutik** [comment]
Anyone alive?

**Comment by pintsized** [comment]
Assuming you mean client SSL certificates, I believe this is still not possible with OpenResty. See: https://github.com/openresty/lua-nginx-module#todo
