### ISSUE TITLE
httpc:request_uri does not set ssl_server_name, breaking SNI

### ISSUE THREAD

**Issue by hackedd** [ledgetech/lua-resty-http#236]
In lua-resty-http 0.15.0, `request_uri` would call `ssl_handshake` with the hostname from the request. In 0.16.0 this is no longer the case, and to get SNI to work, you have to manually pass `ssl_server_name`.

**Comment by hackedd** [comment]
I believe this could be fixed by letting `ssl_server_name` default to the parsed host, similar to `path` and `query`.

**Comment by pintsized** [comment]
Yeah, makes sense to me. Good catch! @Tieske any reason why we shouldn't default to `host` in the absence of `ssl_server_name`?

**Comment by Tieske** [comment]
should it only look at the host from the parsed url, or also at the host header if provided?

**Comment by Tieske** [comment]
old implementation did not take the host header into account

**Comment by pintsized** [comment]
Yeah, I think `host` from the parsed uri makes sense, if not only for backwards compatibility. The point of `request_uri` is to be a "simple" interface ultimately. And if you need to be specific, then we have `ssl_server_name`.

**Comment by Tieske** [comment]
this comment is wrong:
> Note also that fields in `params` will override relevant components of the `uri` if specified.

considering the `0.15` code: https://github.com/ledgetech/lua-resty-http/blob/v0.15/lib/resty/http.lua#L843-L845
(behaviour in `0.16` is same as `0.15`)

Should be
> Note also that fields `path`, and `query`, in `params` will override relevant components of the `uri` if specified (`scheme`, `host`, and `port` will always be taken from the `uri`).

**Comment by pintsized** [comment]
Yeah right. Ok, I'll put a PR together to fix this up, unless you're already on the case?

**Comment by Tieske** [comment]
hold on ...

**Comment by Tieske** [comment]
there ^^

**Comment by pintsized** [comment]
Merged and uploaded to [luarocks](https://luarocks.org/modules/pintsized/lua-resty-http). Thanks all.

Note `opm` releases are waiting on [this opm fix](https://github.com/openresty/opm/pull/85) to be merged and deployed before I can upload again :/
