### ISSUE TITLE
OPM release for 0.16

### ISSUE THREAD

**Issue by hamishforbes** [ledgetech/lua-resty-http#245]
Currently only available on Luarocks but it's a bit of a pita if other packages are installed from OPM and depend on resty-http
You have to start messing with package paths to try and load the luarocks resty-http first etc

**Comment by pintsized** [comment]
Yep, will do. I was just waiting on https://github.com/openresty/opm/pull/85.

**Comment by hamishforbes** [comment]
Doh! I think I still have an old style GitHub token setup, I'll see if I can push out an OPM release in Monday

**Comment by hamishforbes** [comment]
https://opm.openresty.org/package/ledgetech/lua-resty-http/  🎉
