### ISSUE TITLE
how to send file body, like file upload

### ISSUE THREAD

**Issue by xiaoliu10** [ledgetech/lua-resty-http#247]
I want to send files, but I can't find examples or documents
like send local file to other server

**Comment by xiaoliu10** [comment]
Send a file, such as a local file, read the file stream, and then send it to another server

**Comment by pintsized** [comment]
Again, this is not the best place to ask for help on how to create an OpenResty based solution. I'd suggest reaching out for help on the OpenResty mailing list or other forums.
