### ISSUE TITLE
Can this library send a fire-and-forget request?

### ISSUE THREAD

**Issue by travispeloton** [ledgetech/lua-resty-http#248]
Can this library send a fire-and-forget request where we do not want to wait for the response?

I see: https://github.com/ledgetech/lua-resty-http/blob/0ce55d6d15da140ecc5966fa848204c6fd9074e8/lib/resty/http.lua#L876

**Comment by pintsized** [comment]
Yes, if you want to send a request but not wait on it at all, then you could place it onto another light thread using `ngx.timer.at`, and have your closure update some state. You won't know *when* it is done however, but you can log failures, for example.

Note there's nothing special about `lua-resty-http` here - this is just a standard `lua-nginx-module` technique.
