### ISSUE TITLE
Does the scope of http.new() matter for keep-alives and pooling?

### ISSUE THREAD

**Issue by travispeloton** [ledgetech/lua-resty-http#249]
Do we need `http.new()` to be in an outer-scope (e.g., global) in order to best take advantage of keep-alives and pooling?

Or, can `http.new()` be close to where HTTP requests are made without any downside?

**Comment by pintsized** [comment]
It's generally very important never to share objects in a global scope with OpenResty, unless you are very sure about what you are doing.

Creating a new http client object is relatively cheap, and the connection will be reused depending on the context - so yes, calling `http.new()` close to where the request is made is quite typical. Generally one would not reuse that object unless it should definitely use the same connection. Keep in mind that the server may close the connection for you, so generally going back through a connection phase (which will try to reuse connections from the pool transparently) is what you want.

**Comment by ankitjain28may** [comment]
@pintsized If we wont make it global, would it use the pool (existing keep-alive connections) since here its mentioned that it will affect the keep-alive pool connection if we re-instantiate the objects again and again - https://github.com/ledgetech/lua-resty-http/issues/160#issuecomment-748010442

**Comment by ankitjain28may** [comment]
@pintsized For context, I have written a custom plugin for Kong using this library and for every request, our plugin gets executed and using `request_uri` after initializing the object on every req and seems we are not able to use the keepalive connection pool.
But, when I try to make that http.new() global so I can use the pool, I am getting bad request in the log.

Is there a way I can use the connection pool effectively?

**Comment by travispeloton** [comment]
No, you cannot make it global. Here is an example of using keep-alive and connection pools. The way this works is not intuitive, but I can confirm the code below works properly. Look at the OpenResty HTTP client docs for more details on what the settings mean.

```
  local http_client = http.new()
  http_client:set_timeouts(plugin_conf.connect_timeout, plugin_conf.send_timeout, plugin_conf.read_timeout)
  
    -- plugin_conf.connect_timeout is also the backlog timeout, when all pool connections are taken
  local conn, err = http_client:connect {
    scheme = scheme,
    host = host,
    port = port,
    pool = host .. ":" .. port,
    pool_size = plugin_conf.pool_size,
    backlog = plugin_conf.pool_backlog,
  }
  if not conn then
    return nil, err
  end
  
    -- TODO the following proves whether or not keep alive is working
  local reused_times, _ = http_client:get_reused_times()
  kong.log.info("Connection reused_times=", reused_times)

  local response, err = http_client:request {
    version = 1.1,
    path = path,
    query = query,
    method = "POST",
    body = "key=value",
    headers = {
      ["Content-Type"] = "application/x-www-form-urlencoded",
    }
  }
  if not response then
    http_client:close()
    return nil, err
  end

  local body, err = response:read_body()
  if not body then
    http_client:close()
    return nil, err
  end
  response.body = body

  -- keep-alive errors only mean that the connection was closed
  local keep_alive, err = http_client:set_keepalive(plugin_conf.max_idle_timeout, plugin_conf.pool_size)
  if not keep_alive then
    kong.log.warn("keep-alive failed err=", err)
  elseif keep_alive == 2 then
    kong.log.info("keep-alive failed; connection-close requested")
  end
```

**Comment by pintsized** [comment]
> our plugin gets executed and using `request_uri` after initializing the object on every req and seems we are not able to use the keepalive connection pool. But, when I try to make that http.new() global so I can use the pool, I am getting bad request in the log.

There are lots of perfectly valid reasons why you might not see the connection reuse you are hoping for. Maybe your connection was closed by the server (cannot be reused). Maybe you have multiple workers (each worker has its own pool). Maybe the connections in the pool exceeded their timeout. Etc etc.

It certainly has nothing to do with your `http` object being global, so please never do that.
