### ISSUE TITLE
Streamed request mode not working in WSL

### ISSUE THREAD

**Issue by 8kbenchmk** [ledgetech/lua-resty-http#250]
after 4-5 rounds of read body,  stuck then timeout

error.log
2021/09/16 01:54:15 [info] 2570#0: *214 client timed out (110: Connection timed out) while waiting for request, client: 127.0.0.1, server: 0.0.0.0:80
2021/09/16 01:54:15 [error] 2570#0: *213 lua tcp socket read timed out, client: 127.0.0.1, server: localhost, request: "GET /cliff_16.png HTTP/1.1", host: "127.0.0.1"
2021/09/16 01:54:15 [notice] 2570#0: *213 [lua] cache.lua:57: try(): timeout, client: 127.0.0.1, server: localhost, request: "GET /cliff_16.png HTTP/1.1", host: "127.0.0.1"

**Comment by pintsized** [comment]
Do you have any further evidence that this is related to a bug in this library? That is, are you sure your socket is not simply timing out for other reasons? Have you [configured timeouts](https://github.com/ledgetech/lua-resty-http#set_timeouts)?

**Comment by 8kbenchmk** [comment]
> Do you have any further evidence that this is related to a bug in this library? That is, are you sure your socket is not simply timing out for other reasons? Have you [configured timeouts](https://github.com/ledgetech/lua-resty-http#set_timeouts)?

I have try to make same work on proxy_pass with upstream and also get timeout, so i think that's a problem of kernel of WSL. later I update my WSL to WSL2, everything goes ok!
