### ISSUE TITLE
tcpsock:sslhandshake Return Value Not Reflected

### ISSUE THREAD

**Issue by GuyLewin** [ledgetech/lua-resty-http#252]
Version 1.6 introduced a unified `httpc:connect()` method for connecting to a server, and deprecated the old `httpc:ssl_handshake()` method.
We currently rely on the `session` parameter returned from `httpc:ssl_handshake()` (which is returned from [tcpsock:sslhandshake](https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake)) in order to make some validations on the SSL session object.
We'd love to have a way to reflect this value back to the caller of the new `httpc:connect()` API.

**Comment by pintsized** [comment]
I guess something like `local ok, err, ssl_session = httpc:connect(options)` ?
