### ISSUE TITLE
Does this module support the two-way ssl?

### ISSUE THREAD

**Issue by avrtercel** [ledgetech/lua-resty-http#257]
Hello sir, thanks for your hard work. I am a new user of openresty, and find your work by chance. does this module support the two-way ssl ? Thanks for your advice.

**Comment by pintsized** [comment]
I'm assuming you mean mutual TLS? Short answer is no, because OpenResty has no facility for this over cosockets. There is an open [PR](https://github.com/openresty/lua-nginx-module/pull/1602), so we might get there one day.
