### ISSUE TITLE
Can't find the http.lua file

### ISSUE THREAD

**Issue by shaoyangyu** [ledgetech/lua-resty-http#26]
HI,
I am new to Nginx and ngx_lua,the below problem could be very simple reason caused that, but I don't know why. I use resty.http like below, but error message always the http.lua can't be found in the below path. but I checked the http.lua is there with file. any idea?

```
    location /lua{
    content_by_lua '                                                                                                                   
     local http = require "http"                                                                                                       
     local httpc=http.new();                                                                                                           
     ngx.say("hello")'                                                                                                                  
    }
```

stack traceback:
coroutine 0:
        [C]: in function 'require'
        content_by_lua(test.conf:23):2: in function <content_by_lua(test.conf:23):1>, client:, server: 0.0.0.0, request: "POST /lua HTTP/1.1", host: ""
2014/12/29 00:21:05 [error] 14929#0: *10 lua entry thread aborted: runtime error: content_by_lua(test.conf:23):2: module 'http' not found:
        no field package.preload['http']
        no file '/home/shaoyang/tools/lua-resty-http/lib/resty/http.lua'
        no file './http.so'
        no file '/usr/local/lib/lua/5.1/http.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        content_by_lua(test.conf:23):2: in function <content_by_lua(test.conf:23):1>, client:  , server: 0.0.0.0, request: "POST /lua HTTP/1.1", host: " "
# ^C

$ file /home/shaoyang/tools/lua-resty-http/lib/resty/http.lua
/home/shaoyang/tools/lua-resty-http/lib/resty/http.lua: ASCII English text

**Comment by ww110052181** [comment]
@shaoyangyu
how do you solve this problem?
