### ISSUE TITLE
is httpc:request support http range protocol?

### ISSUE THREAD

**Issue by hac135** [ledgetech/lua-resty-http#260]
hi, thanks for sharing the code , I want to know if http range protocol is support in httpc:request method

**Comment by pintsized** [comment]
It is "supported", in the sense that it won't get in the way of you sending a range request. The important work of a range request happens on the server side - the client just needs to set the appropriate headers.

If you are proxying and wish to only serve downstream the correct part of the range, that's not something `lua-resty-http` can do for you, but I wrote an implementation of this elsewhere which you're welcome to use a reference: https://github.com/ledgetech/ledge/blob/master/lib/ledge/range.lua
