### ISSUE TITLE
The request_uri method initiates an HTTPS request, and the return result is nil

### ISSUE THREAD

**Issue by yaofaqian** [ledgetech/lua-resty-http#262]
url = 'https://www.qq.com'
local res1, err = httpc:request_uri(url, {
	method = 'GET',
    keepalive_timeout = 2000 -- 毫秒
})

--返回不等于200表示访问失败
if not res1 then
	ngx.say(res1)
else 
	ngx.say(res1.body)
end
ngx.exit(ngx.HTTP_OK)

--res1 is nil  I'm confused

**Comment by pintsized** [comment]
`res1` will be `nil` if any kind of error occurred - a connection error, any kind of socket send / receive failure etc. The reason will be in your `err` variable.
