### ISSUE TITLE
Allow connect timeout to be specified for request_uri?

### ISSUE THREAD

**Issue by alexdowad** [ledgetech/lua-resty-http#268]
For users who want to make a single HTTP(S) request and aren't worried about the entire response being buffered in memory, the `request_uri` API is much more convenient than the streaming one.

However, there are cases where one might want to limit how long `request_uri` will take. When the `connect`/`request` API is used, connect and read timeouts can be set, but it seems this can't be done with `request_uri`.

Would it be a good idea to add optional parameters to `request_uri` which would allow setting timeouts?

**Comment by pintsized** [comment]
Sorry for the very slow response, but this isn't true. You can call `httpc:set_timeouts` before calling `http:request_uri`. It simply passes the call down to the inner cosocket `settimeouts` function.

**Comment by alexdowad** [comment]
OK, thanks.
