### ISSUE TITLE
call request_uri() , send request successful and server responsed, but request_uri is blocked

### ISSUE THREAD

**Issue by leety1984** [ledgetech/lua-resty-http#272]
We use httpc:request_uri() in production environment, and has a large number of requests to call a micro-service.
Sometimes we found in _chunked_body_reader function,  co_yield(str) does not yield and suspend the execution：
max_chunk_size = co_yield(str) or default_chunk_size
then  in this function:  _read_body(res), coroutine is blocked in this call:
local chunk, err
    repeat
        chunk, err = reader()  -- blocked here 

After a few senconds, Called micro-service close the connection, and we got a Close_wait  status TCP coonction。
We add some debug logs, but have no further progress， Thanks

**Comment by pintsized** [comment]
This has to be something at the network or OS layer. From our point of view, the read operation is expecting data but not getting anything, and will eventually time out, which is to be expected.

Closing, but please reopen if you think this assessment is incorrect.
