### ISSUE TITLE
how to post json by request url,it seems does not support send json params

### ISSUE THREAD

**Issue by Wangxiaobin123** [ledgetech/lua-resty-http#273]
local res, err = httpc:request_uri("XXXX", {
                ssl_verify = false,
                keepalive_timeout = 2000,
                method = "POST",
                body = cjson.encode("{\"token\":\"aaa\"}"),
                headers = {
                        ["Content-Type"] = "application/json;charset=UTF-8"
                }
        })

**Comment by pintsized** [comment]
You are using `cjson` incorrectly. If you have a JSON string, just send that as the body. If you have some Lua values, use `cjson.encode` to convert them to a JSON string.
