### ISSUE TITLE
API disabled in the context of content_by_lua*

### ISSUE THREAD

**Issue by ndragon798** [ledgetech/lua-resty-http#277]
Hi,

For some reason I'm getting `API disabled in the context of content_by_lua*` when attempting to run 

`   
 location / {

        proxy_pass http://dockerhost2.home:3000/;

        mirror /mirror;

        mirror_request_body on;

        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

        # client_body_in_file_only on;
    }

    location = /mirror {

        internal;

        content_by_lua_block {

            resp_bod = string.sub(ngx.arg[1], 1, 1000)

            ngx.log(ngx.ERR,resp_bod,"Test123")

        }

    }

`

Full Error 
`2022/08/08 15:04:53 [error] 9#9: *669944 lua entry thread aborted: runtime error: content_by_lua(removed.com:32):2: API disabled in the context of content_by_lua*
stack traceback:
coroutine 0:
	[C]: in function '__index'
	content_by_lua(removed.com:32):2: in main chunk, client: 10.0.0.1, server: removed.com, request: "GET / HTTP/2.0", subrequest: "/mirror", host: "removed.com"
`

Do you know why this is happening? I thought that this could be used in the content_by_lua_block. I've also tried with access_by_lua_block and I'm getting the same error.

**Comment by pintsized** [comment]
What makes you think this has anything to do with `lua-resty-http`?

I don't really understand your example code. You appear to be using the `proxy_pass` module to proxy an internal location, which has a `content_by_lua` phase handler that uses `ngx.arg`, which itself is only available in `set_by_lua` and `body_filter_by_lua` phase handlers?

Respectfully, I would encourage a more thorough read of the OpenResty / lua-nginx-module documentation: https://github.com/openresty/lua-nginx-module
