### ISSUE TITLE
domain could not be resolved 

### ISSUE THREAD

**Issue by bnchdan** [ledgetech/lua-resty-http#280]
Hi,

I have this issue when I am trying to make a POST request from a Lua Nginx script.

`2022/09/29 12:33:28 [error] 9726#9726: *1 [lua] main.lua:28: request failed: example.com could not be resolved (110: Operation timed out), `

Should I set something else in the Nginx config?

**Comment by pintsized** [comment]
Have you configured a resolver? https://github.com/openresty/lua-nginx-module/#tcpsockconnect

**Comment by bnchdan** [comment]
> Have you configured a resolver? https://github.com/openresty/lua-nginx-module/#tcpsockconnect

yes

**Comment by bnchdan** [comment]
I didn't fix it, but the error is not caused by the module
