### ISSUE TITLE
httpc:set_timeouts doesn't support DNS

### ISSUE THREAD

**Issue by rweichler** [ledgetech/lua-resty-http#286]
## Repro steps

1. Be on a server with no internet connection
2.
```lua
local httpc = require 'resty.http'.new()
httpc:set_timeouts(2, 2, 2)
assert(httpc:request_uri('https://google.com', {
    ssl_verify = false,
}))
```

## Expected

Timeout after 2ms

## Actual

It hangs for much longer, and finally errors with `google.com could not be resolved`

**Comment by rweichler** [comment]
Oh I see, this seems to be an issue with `ngx.socket.tcp`, not this library, I'll ask the OpenResty mailing list

**Comment by anup-krai** [comment]
Hi @rweichler , I am also facing the same issue, were you able to resolve this?

**Comment by pintsized** [comment]
DNS resolution does not happen here, it happens transparently by the underlying `cosocket` according to your Nginx resolver config. Once DNS resolution is complete, a connection will be attempting according to the timeouts you specify here, but there must be a resolved IP address to connect to.

In other words, if you have DNS resolution timeout issues, you need to configure the Nginx resolver differently: https://nginx.org/en/docs/http/ngx_http_core_module.html#resolver_timeout

**Comment by souravs17031999** [comment]
@pintsized I am also facing DNS issues , is there a way to enable nginx dns logs ?
