### ISSUE TITLE
domain could not be resolved (110: Operation timed out)

### ISSUE THREAD

**Issue by zffocussss** [ledgetech/lua-resty-http#303]
Hi team:
  I am running openresty as a pod in k8s,but when some http requests are sent by lua-resty-http module,there are so many dns issues.
  I use tcpdump to catch the network traffic between my openresty pods and coredns pods which is responsible for dns resolution.
the process is ok in my view.
 can some one help me about it?

nginx version: openresty/1.21.4.1
lua-resty-http version: 0.17.1-0
k8s version: 1.26 Alibaba Cloud k8s service

error logs

![image](https://github.com/ledgetech/lua-resty-http/assets/46145695/ebd34b9d-0525-4cd3-afd8-fec131e11941)

**Comment by pintsized** [comment]
This has nothing to do with this library. DNS resolution is handled by OpenResty / Nginx and timeouts will occur according to your resolver configuration: https://nginx.org/en/docs/http/ngx_http_core_module.html#resolver_timeout
