### ISSUE TITLE
ngx是空值

### ISSUE THREAD

**Issue by oneStarCai** [ledgetech/lua-resty-http#304]
./lib/resty/http.lua:4: attempt to index a nil value (local 'ngx')，需要安装ngx库吗？

**Comment by pintsized** [comment]
This library is designed to work with https://github.com/openresty/lua-nginx-module or a.k.a. "OpenResty". It will not work in a pure Lua environment.

**Comment by oneStarCai** [comment]
您的邮件已收到，我会尽快查看并回复。。。

**Comment by oneStarCai** [comment]
I want to run it in a pure Lua environment, is it possible?

**Comment by pintsized** [comment]
No, it is a "resty" module, not a pure Lua module. Try: https://github.com/daurnimator/lua-http
