### ISSUE TITLE
socks5 proxy support

### ISSUE THREAD

**Issue by fuchaoqun** [ledgetech/lua-resty-http#84]
can lua-resty-http add socks5 proxy support?

**Comment by pintsized** [comment]
Pull requests welcome! ;)

**Comment by tst2005** [comment]
maybe [lua-resty-socks5](https://github.com/starius/lua-resty-socks5) should help.

**Comment by pintsized** [comment]
> maybe [lua-resty-socks5](https://github.com/starius/lua-resty-socks5) should help.

I haven't tested this, but yes I agree that would be the right approach.
